### ISSUE TITLE
Text Color

### ISSUE THREAD

**Issue by lorisgir** [youdao-ai/SRNet-Datagen#7]
Hi, thanks for your hard work. I have a question, is it possible to generate data with only black or white text and with full opacity(no trasparency at all) only by tweaking config params?

**Comment by yxgeee** [comment]
@lorisgir Hi, I am also confused about how to disable transparency. Could you give any suggestions? Thanks!

**Comment by lorisgir** [comment]
Hi, I didn't really figure it out. I just managed to set custom font and color to the text
